spring.application.name=sum-it_backend

#Config Cluster MongoDB
#spring.data.mongodb.host=
#spring.data.mongodb.port=
#spring.data.mongodb.database=
#spring.data.mongodb.username=
#spring.data.mongodb.password=

spring.data.mongodb.uri=${MONGODB_URL}
logging.level.org.springframework.data.mongodb.core=DEBUG

#JWT Config
jwt.cookie=AUTH-TOKEN
jwt.expires_in=900
jwt.secret=${JWT_SECRET}

