spring.application.name=sum-it_backend

#Config Cluster MongoDB
#spring.data.mongodb.host=
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=sum-it_database
#spring.data.mongodb.username=redandblackdev
#spring.data.mongodb.password=ROOTKiwikaki0906++

spring.data.mongodb.uri=mongodb+srv://redandblackdev:ROOTKiwikaki0906@sum-it-backend.wmjde.mongodb.net/sum-it_database?retryWrites=true&w=majority&appName=Sum-it-backend
logging.level.org.springframework.data.mongodb.core=DEBUG